apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileuploader-pv-claim
  labels:
    app: fileuploader
  namespace: test
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce