apiVersion: v1
kind: ReplicationController
metadata:
  name: fileuploader-rc
  namespace: test
  labels:
    app: fileuploader-rc
spec:
  replicas: 3
  selector:
      app: fileuploader-rc
      anotherapp: fileuploader-rc1
  template:
    metadata:
      labels:
        app: fileuploader-rc
        anotherapp: fileuploader-rc1
    spec:
      containers:
        - name:  fileuploader-rc
          image: jpalaparthi/fileuploader
          ports:
            - containerPort: 50080
