apiVersion: v1
kind: Service
metadata:
  name: fileuploader
  namespace: default
spec:
  type: NodePort
  selector:
    app: fileuploader
  ports:
  - port: 50080
    targetPort: 50080
    nodePort: 31000
