apiVersion: v1
kind: Pod
metadata:
  name: fileuploader
  namespace: test
  labels:
    app: fileuploader
spec:
  containers:
  - name: uploader
    image: jpalaparthi/fileuploader
    resources:
      requests:
         memory: "64Mi"
         cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: nginx
    image: nginx
    resources:
      requests:
         memory: "64Mi"
         cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 50080
  volumes:
    - name: uploads